### ISSUE TITLE
python3 wildfire.py -S localhost -P 3000 --start --scan. The Server is running

### ISSUE THREAD

**Issue by HCXibm** [R-s0n/ars0n-framework#15]
Traceback (most recent call last):
  File "/home/kali/ars0n-framework/toolkit/wildfire.py", line 228, in <module>
    main(args)
  File "/home/kali/ars0n-framework/toolkit/wildfire.py", line 212, in main
    start(args)
  File "/home/kali/ars0n-framework/toolkit/wildfire.py", line 36, in start
    fqdn_json = json.loads(res.text)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by R-s0n** [comment]
Closing since there is not enough information to troubleshoot
