### ISSUE TITLE
toolkit-service.py is causing error

### ISSUE THREAD

**Issue by AliYar-Khan** [R-s0n/ars0n-framework#53]
I have installed the framework but facing this error

```
Traceback (most recent call last):
  File "/home/kali/Downloads/ars0n-framework/toolkit/toolkit-service.py", line 1, in <module>
    from flask import Flask, jsonify, request
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 34, in <module>
    from . import cli
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 15, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (/usr/local/lib/python3.11/dist-packages/click/core.py)

```

What is the issue here?

**Comment by ekivolowitz** [comment]
You probably need to rerun the pip install step. `click` is a package from the pallets project (same people that make flask).

**Comment by AliYar-Khan** [comment]
I was able to install it. there was a missing dependency called black or something

**Comment by R-s0n** [comment]
Something has gone wrong with the Flask installation.  Are you running the framework on a clean version of Kali?  This usually happens when another version of Python is installed.

**Comment by AliYar-Khan** [comment]
probably yes it was the issue

**Comment by ShadyEshak** [comment]
Traceback (most recent call last):
  File "toolkit-service.py", line 1, in <module>
    from flask import Flask, jsonify, request
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

**Comment by imaltaf** [comment]
just enter " pip install flask psutil " in terminal
